spring:
  application:
    name: code.assignment

# Actuator and Prometheus configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

kafka:
  bootstrap-servers: localhost:9092
  topic:
    transactions: transactions
    recon: recon
  consumer:
    group-id: transaction-consumer-group

alert:
  amount-threshold: 10000
  watchlist-accounts:
    - "suspicious-account-1"
    - "suspicious-account-2"
  webhook:
    url: "http://localhost:8080/webhook/alerts"
    timeout-ms: 5000

logging:
  level:
    com.shaype.code.assignment: INFO
    org.apache.kafka: WARN